import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '1861', name: "熊谷組" },
  { code: '1870', name: "矢作建設工業" },
  { code: '1873', name: "日本ハウスホールディングス" },
  { code: '1879', name: "新日本建設" },
  { code: '1888', name: "若築建設" },
  { code: '1893', name: "五洋建設" },
  { code: '1898', name: "世紀東急工業" },
  { code: '2264', name: "森永乳業" },
  { code: '2266', name: "六甲バター" },
  { code: '2270', name: "雪印メグミルク" },
  { code: '2288', name: "丸大食品" },
  { code: '2292', name: "Ｓ Ｆｏｏｄｓ" },
  { code: '2294', name: "柿安本店" },
  { code: '2296', name: "伊藤ハム米久ホールディングス" },
  { code: '2311', name: "エプコ" },
  { code: '2341', name: "アルバイトタイムス" },
  { code: '2342', name: "トランスジェニックグループ" },
  { code: '2376', name: "サイネックス" },
  { code: '2393', name: "日本ケアサプライ" },
  { code: '2438', name: "アスカネット" },
  { code: '246A', name: "アスア" },
  { code: '2497', name: "ユナイテッド" },
  { code: '2501', name: "サッポロホールディングス" },
  { code: '2531', name: "宝ホールディングス" },
  { code: '2533', name: "オエノンホールディングス" },
  { code: '264A', name: "Ｓｃｈｏｏ" },
  { code: '2778', name: "パレモ・ホールディングス" },
  { code: '2796', name: "ファーマライズホールディングス" },
  { code: '286A', name: "ユカリア" },
  { code: '288A', name: "ラクサス・テクノロジーズ" },
  { code: '291A', name: "リスキル" },
  { code: '296A', name: "令和アカウンティング・ホールディングス" },
  { code: '297A', name: "アルピコホールディングス" },
  { code: '298A', name: "ＧＶＡ ＴＥＣＨ" },
  { code: '299A', name: "クラシル" },
  { code: '3024', name: "クリエイト" },
  { code: '302A', name: "ビースタイルホールディングス" },
  { code: '3035', name: "ケイティケイ" },
  { code: '303A', name: "ｖｉｓｕｍｏ" },
  { code: '3041', name: "ビューティカダンホールディングス" },
  { code: '3042', name: "セキュアヴェイル" },
  { code: '3045', name: "カワサキ" },
  { code: '304A', name: "フォルシア" },
  { code: '3079', name: "ディーブイエックス" },
  { code: '3089', name: "テクノアルファ" },
  { code: '3091', name: "ブロンコビリー" },
  { code: '3093', name: "トレジャー・ファクトリー" },
  { code: '3097', name: "物語コーポレーション" },
  { code: '3131', name: "シンデン・ハイテックス" },
  { code: '3143', name: "オーウイル" },
  { code: '3157', name: "ジオリーブグループ" },
  { code: '3160', name: "大光" },
  { code: '3179', name: "シュッピン" },
  { code: '3182', name: "オイシックス・ラ・大地" },
  { code: '3193', name: "エターナルホスピタリティグループ" },
  { code: '3196', name: "ホットランドホールディングス" },
  { code: '323A', name: "フライヤー" },
  { code: '324A', name: "ブッキングリゾート" },
  { code: '3286', name: "トラストホールディングス" },
  { code: '3293', name: "アズマハウス" },
  { code: '330A', name: "ＴａｌｅｎｔＸ" },
  { code: '332A', name: "ミーク" },
  { code: '334A', name: "ビジュアル・プロセッシング・ジャパン" },
  { code: '335A', name: "ミライロ" },
  { code: '336A', name: "ダイナミックマッププラットフォーム" },
  { code: '338A', name: "ＺｅｎｍｕＴｅｃｈ" },
  { code: '3393', name: "スターティアホールディングス" },
  { code: '340A', name: "ジグザグ" },
  { code: '3482', name: "ロードスターキャピタル" },
  { code: '3496', name: "アズーム" },
  { code: '3498', name: "霞ヶ関キャピタル" },
  { code: '3622', name: "ネットイヤーグループ" },
  { code: '3627', name: "テクミラホールディングス" },
  { code: '3639', name: "ボルテージ" },
  { code: '3640', name: "電算" },
  { code: '3641', name: "パピレス" },
  { code: '3647', name: "アスリナ" },
  { code: '3648', name: "ＡＧＳ" },
  { code: '3687', name: "フィックスターズ" },
  { code: '3694', name: "オプティム" },
  { code: '3696', name: "セレス" },
  { code: '3741', name: "セック" },
  { code: '3763', name: "プロシップ" },
  { code: '3778', name: "さくらインターネット" },
  { code: '3788', name: "ＧＭＯグローバルサイン・ホールディングス" },
  { code: '3834', name: "朝日ネット" },
  { code: '4082', name: "第一稀元素化学工業" },
  { code: '4088', name: "エア・ウォーター" },
  { code: '4091', name: "日本酸素ホールディングス" },
  { code: '4095', name: "日本パーカライジング" },
  { code: '4099', name: "四国化成ホールディングス" },
  { code: '4109', name: "ステラ ケミファ" },
  { code: '4112', name: "保土谷化学工業" },
  { code: '4116', name: "大日精化工業" },
  { code: '4235', name: "ウルトラファブリックス・ホールディングス" },
  { code: '4237', name: "フジプレアム" },
  { code: '4238', name: "ミライアル" },
  { code: '4240', name: "クラスターテクノロジー" },
  { code: '4241', name: "アテクト" },
  { code: '4242', name: "タカギセイコー" },
  { code: '4243', name: "ニックス" },
  { code: '4247', name: "ポバール興業" },
  { code: '4337', name: "ぴあ" },
  { code: '4343', name: "イオンファンタジー" },
  { code: '4345', name: "シーティーエス" },
  { code: '4433', name: "ヒト・コミュニケーションズ・ホールディングス" },
  { code: '4554', name: "富士製薬工業" },
  { code: '4559', name: "ゼリア新薬工業" },
  { code: '4565', name: "ネクセラファーマ" },
  { code: '4569', name: "杏林製薬" },
  { code: '4577', name: "ダイト" },
  { code: '4578', name: "大塚ホールディングス" },
  { code: '4587', name: "ペプチドリーム" },
  { code: '4592', name: "サンバイオ" },
  { code: '4594', name: "ブライトパス・バイオ" },
  { code: '4596', name: "窪田製薬ホールディングス" },
  { code: '4597', name: "ソレイジア・ファーマ" },
  { code: '4598', name: "Ｄｅｌｔａ－Ｆｌｙ Ｐｈａｒｍａ" },
  { code: '4599', name: "ステムリム" },
  { code: '4658', name: "日本空調サービス" },
  { code: '4666', name: "パーク２４" },
  { code: '4668', name: "明光ネットワークジャパン" },
  { code: '4714', name: "リソー教育グループ" },
  { code: '4718', name: "早稲田アカデミー" },
  { code: '4763', name: "クリーク・アンド・リバー社" },
  { code: '4765', name: "ＳＢＩグローバルアセットマネジメント" },
  { code: '4809', name: "パラカ" },
  { code: '4881', name: "ファンペップ" },
  { code: '4882', name: "ペルセウスプロテオミクス" },
  { code: '4883', name: "モダリス" },
  { code: '4884', name: "クリングルファーマ" },
  { code: '4886', name: "あすか製薬ホールディングス" },
  { code: '4887', name: "サワイグループホールディングス" },
  { code: '4888', name: "ステラファーマ" },
  { code: '546A', name: "ＭＩＲＡＩＮＩホールディングス" },
  { code: '5888', name: "ＤＡＩＷＡ ＣＹＣＬＥ" },
  { code: '5892', name: "ｙｕｔｏｒｉ" },
  { code: '5981', name: "東京製綱" },
  { code: '5988', name: "パイオラックス" },
  { code: '5989', name: "エイチワン" },
  { code: '6203', name: "豊和工業" },
  { code: '6217', name: "津田駒工業" },
  { code: '6218', name: "エンシュウ" },
  { code: '6223', name: "西部技研" },
  { code: '6226', name: "守谷輸送機工業" },
  { code: '6231', name: "木村工機" },
  { code: '6238', name: "フリュー" },
  { code: '6247', name: "日阪製作所" },
  { code: '6250', name: "やまびこ" },
  { code: '6258', name: "平田機工" },
  { code: '6266', name: "タツモ" },
  { code: '6268', name: "ナブテスコ" },
  { code: '6272', name: "レオン自動機" },
  { code: '6277', name: "ホソカワミクロン" },
  { code: '6617', name: "東光高岳" },
  { code: '6620', name: "宮越ホールディングス" },
  { code: '6632', name: "ＪＶＣケンウッド" },
  { code: '6638', name: "ミマキエンジニアリング" },
  { code: '6644', name: "大崎電気工業" },
  { code: '6648', name: "かわでん" },
  { code: '6651', name: "日東工業" },
  { code: '6652', name: "ＩＤＥＣ" },
  { code: '6654', name: "不二電機工業" },
  { code: '6656', name: "インスペック" },
  { code: '6658', name: "シライ電子工業" },
  { code: '6659', name: "メディアリンクス" },
  { code: '6664', name: "オプトエレクトロニクス" },
  { code: '6666', name: "リバーエレテック" },
  { code: '6668', name: "アドテック プラズマ テクノロジー" },
  { code: '6674', name: "ジーエス・ユアサ コーポレーション" },
  { code: '6675', name: "サクサ" },
  { code: '7112', name: "キューブ" },
  { code: '7128', name: "ユニソルホールディングス" },
  { code: '7133', name: "ＨＹＵＧＡ ＰＲＩＭＡＲＹ ＣＡＲＥ" },
  { code: '7138', name: "ＴＯＲＩＣＯ" },
  { code: '7140', name: "ペットゴー" },
  { code: '7239', name: "タチエス" },
  { code: '7240', name: "ＮＯＫ" },
  { code: '7241', name: "フタバ産業" },
  { code: '7245', name: "大同メタル工業" },
  { code: '7246', name: "プレス工業" },
  { code: '7254', name: "ユニバンス" },
  { code: '7255', name: "桜井製作所" },
  { code: '7256', name: "河西工業" },
  { code: '7259', name: "アイシン" },
  { code: '7261', name: "マツダ" },
  { code: '7265', name: "エイケン工業" },
  { code: '7269', name: "スズキ" },
  { code: '7271', name: "安永" },
  { code: '7273', name: "イクヨ" },
  { code: '7277', name: "ＴＢＫ" },
  { code: '7381', name: "ＣＣＩグループ" },
  { code: '7384', name: "プロクレアホールディングス" },
  { code: '7414', name: "小野建" },
  { code: '7438', name: "コンドーテック" },
  { code: '7456', name: "松田産業" },
  { code: '7466', name: "ＳＰＫ" },
  { code: '7482', name: "シモジマ" },
  { code: '7483', name: "ドウシシャ" },
  { code: '7674', name: "ＮＡＴＴＹ ＳＷＡＮＫＹホールディングス" },
  { code: '7694', name: "いつも" },
  { code: '7695', name: "交換できるくん" },
  { code: '7745', name: "Ａ＆Ｄホロンホールディングス" },
  { code: '7747', name: "朝日インテック" },
  { code: '7762', name: "シチズン時計" },
  { code: '7769', name: "リズム" },
  { code: '7780', name: "メニコン" },
  { code: '7979', name: "松風" },
  { code: '7989', name: "立川ブラインド工業" },
  { code: '8050', name: "セイコーグループ" },
  { code: '8086', name: "ニプロ" },
  { code: '8309', name: "三井住友トラストグループ" },
  { code: '8331', name: "千葉銀行" },
  { code: '8334', name: "群馬銀行" },
  { code: '8336', name: "武蔵野銀行" },
  { code: '8337', name: "千葉興業銀行" },
  { code: '8338', name: "筑波銀行" },
  { code: '8593', name: "三菱ＨＣキャピタル" },
  { code: '8697', name: "日本取引所グループ" },
  { code: '8771', name: "イー・ギャランティ" },
  { code: '8793', name: "ＮＥＣキャピタルソリューション" },
  { code: '8803', name: "平和不動産" },
  { code: '8818', name: "京阪神ビルディング" },
  { code: '9045', name: "京阪ホールディングス" },
  { code: '9048', name: "名古屋鉄道" },
  { code: '9052', name: "山陽電気鉄道" },
  { code: '9064', name: "ヤマトホールディングス" },
  { code: '9065', name: "山九" },
  { code: '9068', name: "丸全昭和運輸" },
  { code: '9072', name: "ニッコンホールディングス" },
  { code: '9075', name: "福山通運" },
  { code: '9145', name: "ビーイングホールディングス" },
  { code: '9536', name: "西部ガスホールディングス" },
];

test('keeps at least 1458 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(233);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(233);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1900社');
  await expect(page.locator('#stat-confirmed')).toHaveText('1458社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(1458);
});

test('exposes every structured-expansion-batch-80 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
