import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '130A', name: "Ｖｅｒｉｔａｓ Ｉｎ Ｓｉｌｉｃｏ" },
  { code: '135A', name: "ＶＲＡＩＮ Ｓｏｌｕｔｉｏｎ" },
  { code: '137A', name: "Ｃｏｃｏｌｉｖｅ" },
  { code: '141A', name: "トライアルホールディングス" },
  { code: '142A', name: "ジンジブ" },
  { code: '1433', name: "ベステラ" },
  { code: '143A', name: "イシン" },
  { code: '1447', name: "ＳＡＡＦホールディングス" },
  { code: '145A', name: "Ｌ ｉｓ Ｂ" },
  { code: '148A', name: "ハッチ・ワーク" },
  { code: '149A', name: "シンカ" },
  { code: '150A', name: "ＪＳＨ" },
  { code: '151A', name: "ダイブ" },
  { code: '153A', name: "カウリス" },
  { code: '155A', name: "情報戦略テクノロジー" },
  { code: '1719', name: "安藤・間" },
  { code: '1720', name: "東急建設" },
  { code: '173A', name: "ハンモック" },
  { code: '1766', name: "東建コーポレーション" },
  { code: '177A', name: "コージンバイオ" },
  { code: '1786', name: "オリエンタル白石" },
  { code: '1808', name: "長谷工コーポレーション" },
  { code: '1820', name: "西松建設" },
  { code: '184A', name: "学びエイド" },
  { code: '1860', name: "戸田建設" },
  { code: '1878', name: "大東建託" },
  { code: '189A', name: "Ｄ＆Ｍカンパニー" },
  { code: '1911', name: "住友林業" },
  { code: '1942', name: "関電工" },
  { code: '194A', name: "ＷＯＬＶＥＳ ＨＡＮＤ" },
  { code: '198A', name: "ＰｏｓｔＰｒｉｍｅ" },
  { code: '2001', name: "ニップン" },
  { code: '2004', name: "昭和産業" },
  { code: '2053', name: "中部飼料" },
  { code: '205A', name: "ロゴスホールディングス" },
  { code: '2060', name: "フィード・ワン" },
  { code: '206A', name: "ＰＲＩＳＭ ＢｉｏＬａｂ" },
  { code: '208A', name: "構造計画研究所ホールディングス" },
  { code: '2108', name: "日本甜菜製糖" },
  { code: '2109', name: "ＤＭ三井製糖" },
  { code: '2162', name: "ｎｍｓ ホールディングス" },
  { code: '218A', name: "Ｌｉｂｅｒａｗａｒｅ" },
  { code: '219A', name: "Ｈｅａｒｔｓｅｅｄ" },
  { code: '2207', name: "ｍｅｉｔｏ" },
  { code: '2353', name: "日本駐車場開発" },
  { code: '247A', name: "Ａｉロボティクス" },
  { code: '254A', name: "ＡＩフュージョンキャピタルグループ" },
  { code: '2659', name: "サンエー" },
  { code: '2664', name: "カワチ薬品" },
  { code: '2670', name: "エービーシー・マート" },
  { code: '2674', name: "ハードオフコーポレーション" },
  { code: '2678', name: "アスクル" },
  { code: '2685', name: "アンドエスティＨＤ" },
  { code: '2695', name: "くら寿司" },
  { code: '2721', name: "ジェイホールディングス" },
  { code: '2730', name: "エディオン" },
  { code: '2733', name: "あらた" },
  { code: '2734', name: "サーラコーポレーション" },
  { code: '2737', name: "トーメンデバイス" },
  { code: '2751', name: "テンポスホールディングス" },
  { code: '2760', name: "東京エレクトロン　デバイス" },
  { code: '2768', name: "双日" },
  { code: '278A', name: "Ｔｅｒｒａ Ｄｒｏｎｅ" },
  { code: '3028', name: "アルペン" },
  { code: '3036', name: "アルコニックス" },
  { code: '3063', name: "ジェイグループホールディングス" },
  { code: '3088', name: "マツキヨココカラ＆カンパニー" },
  { code: '3113', name: "ＵＮＩＶＡ・Ｏａｋホールディングス" },
  { code: '3139', name: "ラクト・ジャパン" },
  { code: '3153', name: "八洲電機" },
  { code: '3245', name: "ディア・ライフ" },
  { code: '3349', name: "コスモス薬品" },
  { code: '3433', name: "トーカロ" },
  { code: '3436', name: "ＳＵＭＣＯ" },
  { code: '3443', name: "川田テクノロジーズ" },
  { code: '373A', name: "リップス" },
  { code: '441A', name: "ＮＥ" },
  { code: '4564', name: "オンコセラピー・サイエンス" },
  { code: '4570', name: "免疫生物研究所" },
  { code: '4572', name: "カルナバイオサイエンス" },
  { code: '4575', name: "キャンバス" },
  { code: '4651', name: "サニックスホールディングス" },
  { code: '4934', name: "プレミアアンチエイジング" },
  { code: '4937', name: "Ｗａｑｏｏ" },
  { code: '5016', name: "ＪＸ金属" },
  { code: '5031', name: "モイ" },
  { code: '523A', name: "セイワホールディングス" },
  { code: '5406', name: "神戸製鋼所" },
  { code: '5408', name: "中山製鋼所" },
  { code: '5410', name: "合同製鐵" },
  { code: '5423', name: "東京製鐵" },
  { code: '5440', name: "共英製鋼" },
  { code: '5444', name: "大和工業" },
  { code: '5838', name: "楽天銀行" },
  { code: '6035', name: "アイ・アールジャパンホールディングス" },
  { code: '6166', name: "中村超硬" },
  { code: '6224', name: "ＪＲＣ" },
  { code: '6232', name: "ＡＣＳＬ" },
  { code: '6522', name: "アスタリスク" },
  { code: '6597', name: "ＨＰＣシステムズ" },
  { code: '6696', name: "トラース・オン・プロダクト" },
  { code: '7148', name: "ＦＰＧ" },
  { code: '7157', name: "ライフネット生命保険" },
  { code: '7164', name: "全国保証" },
  { code: '7172', name: "ジャパンインベストメントアドバイザー" },
  { code: '7181', name: "かんぽ生命保険" },
  { code: '7187', name: "ジェイリース" },
  { code: '7213', name: "レシップホールディングス" },
  { code: '7388', name: "ＦＰパートナー" },
  { code: '7453', name: "良品計画" },
  { code: '7476', name: "アズワン" },
  { code: '7774', name: "ジャパン・ティッシュエンジニアリング" },
  { code: '7776', name: "セルシード" },
  { code: '7777', name: "スリー・ディー・マトリックス" },
  { code: '8012', name: "長瀬産業" },
  { code: '8015', name: "豊田通商" },
  { code: '8020', name: "兼松" },
  { code: '8051', name: "山善" },
  { code: '8060', name: "キヤノンマーケティングジャパン" },
  { code: '8088', name: "岩谷産業" },
  { code: '8130', name: "サンゲツ" },
  { code: '8136', name: "サンリオ" },
  { code: '8200', name: "リンガーハット" },
  { code: '8242', name: "エイチ・ツー・オー　リテイリング" },
  { code: '8253', name: "クレディセゾン" },
  { code: '8283', name: "ＰＡＬＴＡＣ" },
  { code: '8424', name: "芙蓉総合リース" },
  { code: '8425', name: "みずほリース" },
  { code: '8613', name: "丸三証券" },
  { code: '8614', name: "東洋証券" },
  { code: '8622', name: "水戸証券" },
  { code: '8804', name: "東京建物" },
  { code: '8830', name: "住友不動産" },
  { code: '9001', name: "東武鉄道" },
  { code: '9006', name: "京浜急行電鉄" },
  { code: '9007', name: "小田急電鉄" },
  { code: '9008', name: "京王電鉄" },
  { code: '9009', name: "京成電鉄" },
  { code: '9010', name: "富士急行" },
  { code: '9110', name: "ＮＳユナイテッド海運" },
  { code: '9119', name: "飯野海運" },
  { code: '9303', name: "住友倉庫" },
  { code: '9304', name: "澁澤倉庫" },
  { code: '9310', name: "日本トランスシティ" },
  { code: '9319', name: "中央倉庫" },
  { code: '9324', name: "安田倉庫" },
  { code: '9326', name: "関通ホールディングス" },
  { code: '9364', name: "上組" },
  { code: '9381', name: "エーアイテイー" },
  { code: '9715', name: "トランス・コスモス" },
  { code: '9716', name: "乃村工藝社" },
  { code: '9722', name: "藤田観光" },
  { code: '9743', name: "丹青社" },
  { code: '9934', name: "因幡電機産業" },
  { code: '9987', name: "スズケン" },
  { code: '9989', name: "サンドラッグ" },
];

test('keeps at least 608 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(156);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(156);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1200社');
  await expect(page.locator('#stat-confirmed')).toHaveText('608社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(608);
});

test('exposes every structured-expansion-batch-73 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
