import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '1814', name: "大末建設" },
  { code: '1833', name: "奥村組" },
  { code: '195A', name: "ＭＵＳＣＡＴ ＧＲＯＵＰ" },
  { code: '2158', name: "ＦＲＯＮＴＥＯ" },
  { code: '2179', name: "成学社" },
  { code: '2180', name: "サニーサイドアップグループ" },
  { code: '2183', name: "リニカル" },
  { code: '2186', name: "ソーバル" },
  { code: '2195', name: "アミタホールディングス" },
  { code: '2211', name: "不二家" },
  { code: '2217', name: "モロゾフ" },
  { code: '2222', name: "寿スピリッツ" },
  { code: '2229', name: "カルビー" },
  { code: '228A', name: "オプロ" },
  { code: '2338', name: "クオンタムソリューションズ" },
  { code: '2345', name: "ＨＯＤＬ１" },
  { code: '2349', name: "エヌアイデイ" },
  { code: '2351', name: "ＡＳＪ" },
  { code: '2370', name: "メディネット" },
  { code: '2385', name: "総医研ホールディングス" },
  { code: '244A', name: "グロースエクスパートナーズ" },
  { code: '2462', name: "ライク" },
  { code: '2475', name: "ＷＤＢホールディングス" },
  { code: '248A', name: "キッズスター" },
  { code: '2491', name: "バリューコマース" },
  { code: '265A', name: "Ｈｍｃｏｍｍ" },
  { code: '269A', name: "Ｓａｐｅｅｔ" },
  { code: '2736', name: "フェスタリアホールディングス" },
  { code: '2742', name: "ハローズ" },
  { code: '2753', name: "あみやき亭" },
  { code: '2763', name: "エフティグループ" },
  { code: '277A', name: "グロービング" },
  { code: '2791', name: "大黒天物産" },
  { code: '281A', name: "インフォメティス" },
  { code: '287A', name: "黒田グループ" },
  { code: '3087', name: "ドトール・日レスホールディングス" },
  { code: '3156', name: "レスター" },
  { code: '3176', name: "三洋貿易" },
  { code: '3180', name: "ビューティガレージ" },
  { code: '3183', name: "ウイン・パートナーズ" },
  { code: '3266', name: "ファンドクリエーショングループ" },
  { code: '3284', name: "フージャースホールディングス" },
  { code: '3457', name: "Ａｎｄ Ｄｏホールディングス" },
  { code: '3465', name: "ケイアイスター不動産" },
  { code: '3479', name: "ＴＫＰ" },
  { code: '3480', name: "ジェイ・エス・ビー" },
  { code: '3556', name: "リネットジャパングループ" },
  { code: '3557', name: "ユナイテッド＆コレクティブ" },
  { code: '3558', name: "ジェイドグループ" },
  { code: '3566', name: "ユニフォームネクスト" },
  { code: '3591', name: "ワコールホールディングス" },
  { code: '3608', name: "ＴＳＩホールディングス" },
  { code: '3663', name: "セルシス" },
  { code: '3678', name: "メディアドゥ" },
  { code: '3679', name: "じげん" },
  { code: '4044', name: "セントラル硝子" },
  { code: '4046', name: "大阪ソーダ" },
  { code: '4047', name: "関東電化工業" },
  { code: '4064', name: "日本カーバイド工業" },
  { code: '4078', name: "堺化学工業" },
  { code: '4119', name: "日本ピグメントホールディングス" },
  { code: '4124', name: "大阪油化工業" },
  { code: '4125', name: "三和油化工業" },
  { code: '4222', name: "児玉化学工業" },
  { code: '4548', name: "生化学工業" },
  { code: '4549', name: "栄研化学" },
  { code: '4552', name: "ＪＣＲファーマ" },
  { code: '4582', name: "シンバイオ製薬" },
  { code: '4583', name: "カイオム・バイオサイエンス" },
  { code: '4584', name: "キッズウェル・バイオ" },
  { code: '4586', name: "メドレックス" },
  { code: '4588', name: "オンコリスバイオファーマ" },
  { code: '4591', name: "リボミック" },
  { code: '5471', name: "大同特殊鋼" },
  { code: '5482', name: "愛知製鋼" },
  { code: '5527', name: "ｐｒｏｐｅｒｔｙ ｔｅｃｈｎｏｌｏｇｉｅｓ" },
  { code: '5532', name: "リアルゲイト" },
  { code: '5537', name: "ＡｌｂａＬｉｎｋ" },
  { code: '5541', name: "大平洋金属" },
  { code: '5563', name: "新日本電工" },
  { code: '556A', name: "犬猫生活" },
  { code: '5602', name: "栗本鐵工所" },
  { code: '5805', name: "ＳＷＣＣ" },
  { code: '5821', name: "平河ヒューテック" },
  { code: '5851', name: "リョービ" },
  { code: '5884', name: "クラダシ" },
  { code: '5946', name: "長府製作所" },
  { code: '5947', name: "リンナイ" },
  { code: '5957', name: "日東精工" },
  { code: '5959', name: "岡部" },
  { code: '5970', name: "ジーテクト" },
  { code: '5975', name: "東プレ" },
  { code: '6150', name: "タケダ機械" },
  { code: '6151', name: "日東工器" },
  { code: '6155', name: "高松機械工業" },
  { code: '6156', name: "エーワン精密" },
  { code: '6158', name: "和井田製作所" },
  { code: '6159', name: "ミクロン精密" },
  { code: '6161', name: "エスティック" },
  { code: '6167', name: "冨士ダイス" },
  { code: '6209', name: "リケンＮＰＲ" },
  { code: '6222', name: "島精機製作所" },
  { code: '6235', name: "オプトラン" },
  { code: '6526', name: "ソシオネクスト" },
  { code: '6588', name: "東芝テック" },
  { code: '6633', name: "ＣＧＳホールディングス" },
  { code: '6634', name: "ＪＮグループ" },
  { code: '6635', name: "大日光・エンジニアリング" },
  { code: '6643', name: "戸上電機製作所" },
  { code: '6647', name: "森尾電機" },
  { code: '7189', name: "西日本フィナンシャルホールディングス" },
  { code: '7220', name: "武蔵精密工業" },
  { code: '7226', name: "極東開発工業" },
  { code: '7231', name: "トピー工業" },
  { code: '7238', name: "曙ブレーキ工業" },
  { code: '7327', name: "第四北越フィナンシャルグループ" },
  { code: '7350', name: "おきなわフィナンシャルグループ" },
  { code: '7729', name: "東京精密" },
  { code: '7731', name: "ニコン" },
  { code: '7734', name: "理研計器" },
  { code: '7740', name: "タムロン" },
  { code: '7744', name: "ノーリツ鋼機" },
  { code: '7749', name: "メディキット" },
  { code: '7760', name: "ＩＭＶ" },
  { code: '7771', name: "日本精密" },
  { code: '7775', name: "大研医器" },
  { code: '7781', name: "平山ホールディングス" },
  { code: '7782', name: "シンシア" },
  { code: '8439', name: "東京センチュリー" },
  { code: '8511', name: "日本証券金融" },
  { code: '8566', name: "リコーリース" },
  { code: '8570', name: "イオンフィナンシャルサービス" },
  { code: '8585', name: "オリエントコーポレーション" },
  { code: '8628', name: "松井証券" },
  { code: '8698', name: "マネックスグループ" },
  { code: '8706', name: "極東証券" },
  { code: '8707', name: "岩井コスモホールディングス" },
  { code: '8708', name: "アイザワ証券グループ" },
  { code: '8739', name: "スパークス・グループ" },
  { code: '9025', name: "鴻池運輸" },
  { code: '9031', name: "西日本鉄道" },
  { code: '9037', name: "ハマキョウレックス" },
  { code: '9039', name: "サカイ引越センター" },
  { code: '9041', name: "近鉄グループホールディングス" },
  { code: '9044', name: "ＮＡＮＫＡＩ" },
  { code: '9059', name: "カンダホールディングス" },
];

test('keeps at least 1150 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(146);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(146);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1500社');
  await expect(page.locator('#stat-confirmed')).toHaveText('1150社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(1150);
});

test('exposes every structured-expansion-batch-78 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
