import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '166A', name: "タスキホールディングス" },
  { code: '1762', name: "高松コンストラクショングループ" },
  { code: '186A', name: "アストロスケールホールディングス" },
  { code: '192A', name: "インテグループ" },
  { code: '212A', name: "フィットイージー" },
  { code: '2148', name: "アイティメディア" },
  { code: '2163', name: "アルトナー" },
  { code: '2175', name: "エス・エム・エス" },
  { code: '2198', name: "アイ・ケイ・ケイホールディングス" },
  { code: '2209', name: "井村屋グループ" },
  { code: '2301', name: "学情" },
  { code: '2307', name: "クロスキャット" },
  { code: '2325', name: "ＮＪＳ" },
  { code: '2331', name: "ＡＬＳＯＫ" },
  { code: '2335', name: "キューブシステム" },
  { code: '2359', name: "コア" },
  { code: '2371', name: "カカクコム" },
  { code: '2378', name: "ルネサンス" },
  { code: '2384', name: "ＳＢＳホールディングス" },
  { code: '2388', name: "ウェッジホールディングス" },
  { code: '2395', name: "新日本科学" },
  { code: '2429', name: "ワールドホールディングス" },
  { code: '2461', name: "ファンコミュニケーションズ" },
  { code: '2492', name: "インフォマート" },
  { code: '2681', name: "ゲオホールディングス" },
  { code: '268A', name: "リガク・ホールディングス" },
  { code: '2726', name: "パルグループホールディングス" },
  { code: '2767', name: "円谷フィールズホールディングス" },
  { code: '2930', name: "北の達人コーポレーション" },
  { code: '2980', name: "ＳＲＥホールディングス" },
  { code: '2982', name: "ＡＤワークスグループ" },
  { code: '2986', name: "ＬＡホールディングス" },
  { code: '3034', name: "クオールホールディングス" },
  { code: '3040', name: "ソリトンシステムズ" },
  { code: '3076', name: "あい ホールディングス" },
  { code: '3101', name: "東洋紡" },
  { code: '3116', name: "トヨタ紡織" },
  { code: '3431', name: "宮地エンジニアリンググループ" },
  { code: '3636', name: "三菱総合研究所" },
  { code: '3673', name: "ブロードリーフ" },
  { code: '368A', name: "北里コーポレーション" },
  { code: '3762', name: "テクマトリックス" },
  { code: '3765', name: "ガンホー・オンライン・エンターテイメント" },
  { code: '3769', name: "ＧＭＯペイメントゲートウェイ" },
  { code: '3774', name: "インターネットイニシアティブ" },
  { code: '3923', name: "ラクス" },
  { code: '4022', name: "ラサ工業" },
  { code: '4027', name: "テイカ" },
  { code: '4028', name: "石原産業" },
  { code: '4041', name: "日本曹達" },
  { code: '4151', name: "協和キリン" },
  { code: '417A', name: "ブルーゾーンホールディングス" },
  { code: '4180', name: "Ａｐｐｉｅｒ　Ｇｒｏｕｐ" },
  { code: '4194', name: "ビジョナル" },
  { code: '4290', name: "プレステージ・インターナショナル" },
  { code: '4301', name: "アミューズ" },
  { code: '4310', name: "ドリームインキュベータ" },
  { code: '4483', name: "ＪＭＤＣ" },
  { code: '4506', name: "住友ファーマ" },
  { code: '4507', name: "塩野義製薬" },
  { code: '4516', name: "日本新薬" },
  { code: '4521', name: "科研製薬" },
  { code: '4527', name: "ロート製薬" },
  { code: '4528', name: "小野薬品工業" },
  { code: '4534', name: "持田製薬" },
  { code: '4680', name: "ラウンドワン" },
  { code: '4681', name: "リゾートトラスト" },
  { code: '4684', name: "オービック" },
  { code: '4686', name: "ジャストシステム" },
  { code: '4694', name: "ビー・エム・エル" },
  { code: '4704', name: "トレンドマイクロ" },
  { code: '471A', name: "ＮＳグループ" },
  { code: '4722', name: "フューチャー" },
  { code: '4732', name: "ユー・エス・エス" },
  { code: '4733', name: "オービックビジネスコンサルタント" },
  { code: '4768', name: "大塚商会" },
  { code: '4812', name: "電通総研" },
  { code: '4819', name: "デジタルガレージ" },
  { code: '4902', name: "コニカミノルタ" },
  { code: '5032', name: "ＡＮＹＣＯＬＯＲ" },
  { code: '5703', name: "日本軽金属ホールディングス" },
  { code: '5831', name: "しずおかフィナンシャルグループ" },
  { code: '5844', name: "京都フィナンシャルグループ" },
  { code: '5902', name: "ホッカンホールディングス" },
  { code: '5911', name: "横河ブリッジホールディングス" },
  { code: '5949', name: "ユニプレス" },
  { code: '6013', name: "タクマ" },
  { code: '6036', name: "ＫｅｅＰｅｒ技研" },
  { code: '6080', name: "Ｍ＆Ａキャピタルパートナーズ" },
  { code: '6101', name: "ツガミ" },
  { code: '6104', name: "芝浦機械" },
  { code: '6118', name: "アイダエンジニアリング" },
  { code: '6135', name: "牧野フライス製作所" },
  { code: '6136', name: "オーエスジー" },
  { code: '6143', name: "ソディック" },
  { code: '6200', name: "インソース" },
  { code: '6376', name: "日機装" },
  { code: '6455', name: "モリタホールディングス" },
  { code: '6507', name: "シンフォニアテクノロジー" },
  { code: '6508', name: "明電舎" },
  { code: '6516', name: "山洋電気" },
  { code: '6517', name: "デンヨー" },
  { code: '6525', name: "ＫＯＫＵＳＡＩ ＥＬＥＣＴＲＩＣ" },
  { code: '6995', name: "東海理化電機製作所" },
  { code: '7167', name: "めぶきフィナンシャルグループ" },
  { code: '7173', name: "東京きらぼしフィナンシャルグループ" },
  { code: '7186', name: "横浜フィナンシャルグループ" },
  { code: '7199', name: "プレミアグループ" },
  { code: '7202', name: "いすゞ自動車" },
  { code: '7318', name: "セレンディップ・ホールディングス" },
  { code: '7326', name: "ＳＢＩインシュアランスグループ" },
  { code: '7383', name: "ネットプロテクションズホールディングス" },
  { code: '7550', name: "ゼンショーホールディングス" },
  { code: '7701', name: "島津製作所" },
  { code: '7715', name: "長野計器" },
  { code: '7721', name: "東京計器" },
  { code: '7723', name: "愛知時計電機" },
  { code: '7725', name: "インターアクション" },
  { code: '7860', name: "エイベックス" },
  { code: '8282', name: "ケーズホールディングス" },
  { code: '8609', name: "岡三証券グループ" },
  { code: '8616', name: "東海東京フィナンシャル・ホールディングス" },
  { code: '8729', name: "ソニーフィナンシャルグループ" },
  { code: '8795', name: "Ｔ＆Ｄホールディングス" },
  { code: '9003', name: "相鉄ホールディングス" },
  { code: '9024', name: "西武ホールディングス" },
  { code: '9270', name: "バリュエンスホールディングス" },
  { code: '9302', name: "三井倉庫ホールディングス" },
  { code: '9336', name: "大栄環境" },
  { code: '9416', name: "ビジョン" },
  { code: '9418', name: "Ｕ－ＮＥＸＴ　ＨＯＬＤＩＮＧＳ" },
  { code: '9435', name: "光通信" },
  { code: '9468', name: "ＫＡＤＯＫＡＷＡ" },
  { code: '9552', name: "クオンツ総研ホールディングス" },
  { code: '9601', name: "松竹" },
  { code: '9603', name: "エイチ・アイ・エス" },
  { code: '9605', name: "東映" },
  { code: '9616', name: "共立メンテナンス" },
  { code: '9621', name: "建設技術研究所" },
  { code: '9672', name: "東京都競馬" },
  { code: '9759', name: "ＮＳＤ" },
];

test('keeps at least 452 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(141);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(141);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1200社');
  await expect(page.locator('#stat-confirmed')).toHaveText('452社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(452);
});

test('exposes every structured-expansion-batch-72 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
