import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '138A', name: "光フードサービス" },
  { code: '1401', name: "エムビーエス" },
  { code: '1418', name: "インターライフホールディングス" },
  { code: '1431', name: "Ｌｉｂ　Ｗｏｒｋ" },
  { code: '1434', name: "ＪＥＳＣＯホールディングス" },
  { code: '1435', name: "ｒｏｂｏｔ　ｈｏｍｅ" },
  { code: '1436', name: "グリーンエナジー＆カンパニー" },
  { code: '1443', name: "技研ホールディングス" },
  { code: '1444', name: "ニッソウ" },
  { code: '146A', name: "コロンビア・ワークス" },
  { code: '1518', name: "三井松島ホールディングス" },
  { code: '160A', name: "アズパートナーズ" },
  { code: '1663', name: "Ｋ＆Ｏエナジーグループ" },
  { code: '1717', name: "明豊ファシリティワークス" },
  { code: '1783', name: "ｆａｎｔａｓｉｓｔａ" },
  { code: '1909', name: "日本ドライケミカル" },
  { code: '196A', name: "ＭＦＳ" },
  { code: '197A', name: "タウンズ" },
  { code: '2122', name: "インタースペース" },
  { code: '2134', name: "北浜キャピタルパートナーズ" },
  { code: '2136', name: "ヒップ" },
  { code: '2139', name: "中広" },
  { code: '2156', name: "セーラー広告" },
  { code: '2193', name: "クックパッド" },
  { code: '220A', name: "Ｆａｂｅｒ Ｃｏｍｐａｎｙ" },
  { code: '2303', name: "ドーン" },
  { code: '2323', name: "ｆｏｎｆｕｎ" },
  { code: '2329', name: "東北新社" },
  { code: '2330', name: "フォーサイド" },
  { code: '2332', name: "クエスト" },
  { code: '2445', name: "タカミヤ" },
  { code: '245A', name: "ＩＮＧＳ" },
  { code: '2586', name: "フルッタフルッタ" },
  { code: '2656', name: "ベクターホールディングス" },
  { code: '2668', name: "タビオ" },
  { code: '2693', name: "ＹＫＴ" },
  { code: '2708', name: "久世" },
  { code: '2934', name: "ジェイフロンティア" },
  { code: '2937', name: "サンクゼール" },
  { code: '2978', name: "ツクルバ" },
  { code: '2981', name: "ランディックス" },
  { code: '2983', name: "アールプランナー" },
  { code: '2997', name: "ストレージ王" },
  { code: '3104', name: "富士紡ホールディングス" },
  { code: '3140', name: "ＢＲＵＮＯ" },
  { code: '3185', name: "夢展望" },
  { code: '3187', name: "ミラタップ" },
  { code: '3224', name: "ゼネラル・オイスター" },
  { code: '3237', name: "イントランス" },
  { code: '3261', name: "グランディーズ" },
  { code: '3359', name: "ｃｏｔｔａ" },
  { code: '3418', name: "バルニバービ" },
  { code: '341A', name: "トヨコー" },
  { code: '3440', name: "日創グループ" },
  { code: '3474', name: "Ｇ－ＦＡＣＴＯＲＹ" },
  { code: '3477', name: "フォーライフ" },
  { code: '3549', name: "クスリのアオキホールディングス" },
  { code: '3550', name: "スタジオアタオ" },
  { code: '3553', name: "共和レザー" },
  { code: '3861', name: "王子ホールディングス" },
  { code: '3878', name: "巴川コーポレーション" },
  { code: '4031', name: "片倉コープアグリ" },
  { code: '4040', name: "南海化学" },
  { code: '4093', name: "東邦アセチレン" },
  { code: '4098', name: "チタン工業" },
  { code: '4100', name: "戸田工業" },
  { code: '4102', name: "丸尾カルシウム" },
  { code: '4107', name: "伊勢化学工業" },
  { code: '4382', name: "ＨＥＲＯＺ" },
  { code: '4420', name: "イーソル" },
  { code: '4434', name: "サーバーワークス" },
  { code: '4512', name: "わかもと製薬" },
  { code: '4524', name: "森下仁丹" },
  { code: '4539', name: "日本ケミファ" },
  { code: '4558', name: "中京医薬品" },
  { code: '4620', name: "藤倉化成" },
  { code: '462A', name: "ＦＵＮＤＩＮＮＯ" },
  { code: '4885', name: "室町ケミカル" },
  { code: '4979', name: "ＯＡＴアグリオ" },
  { code: '5011', name: "ニチレキグループ" },
  { code: '5021', name: "コスモエネルギーホールディングス" },
  { code: '5187', name: "クリエートメディック" },
  { code: '5451', name: "ヨドコウ" },
  { code: '5461', name: "中部鋼鈑" },
  { code: '5463', name: "丸一鋼管" },
  { code: '5702', name: "大紀アルミニウム工業所" },
  { code: '5704', name: "ＪＭＣ" },
  { code: '5706', name: "三井金属" },
  { code: '5726', name: "大阪チタニウムテクノロジーズ" },
  { code: '5741', name: "ＵＡＣＪ" },
  { code: '5757', name: "ＣＫサンエツ" },
  { code: '5834', name: "ＳＢＩリーシングサービス" },
  { code: '5842', name: "インテグラル" },
  { code: '5858', name: "ＳＴＧ" },
  { code: '5991', name: "日本発條" },
  { code: '6016', name: "ジャパンエンジンコーポレーション" },
  { code: '6018', name: "阪神内燃機工業" },
  { code: '6023', name: "ダイハツインフィニアース" },
  { code: '6030', name: "アドベンチャー" },
  { code: '6042', name: "ニッキ" },
  { code: '6125', name: "岡本工作機械製作所" },
  { code: '6137', name: "小池酸素工業" },
  { code: '6138', name: "ダイジェット工業" },
  { code: '6144', name: "西部電機" },
  { code: '6145', name: "ＮＩＴＴＯＫＵ" },
  { code: '6147', name: "ヤマザキ" },
  { code: '6149', name: "小田原エンジニアリング" },
  { code: '6262', name: "ＰＥＧＡＳＵＳ" },
  { code: '6317', name: "北川鉄工所" },
  { code: '6378', name: "木村化工機" },
  { code: '6482', name: "ＹＵＳＨＩＮ" },
  { code: '6485', name: "前澤給装工業" },
  { code: '6493', name: "ＮＩＴＴＡＮ" },
  { code: '6505', name: "東洋電機製造" },
  { code: '6513', name: "オリジン" },
  { code: '6524', name: "湖北工業" },
  { code: '6599', name: "エブレン" },
  { code: '6614', name: "シキノハイテック" },
  { code: '6982', name: "リード" },
  { code: '7014', name: "名村造船所" },
  { code: '7018', name: "内海造船" },
  { code: '7110', name: "クラシコム" },
  { code: '7114', name: "フーディソン" },
  { code: '7122', name: "近畿車輛" },
  { code: '7161', name: "じもとホールディングス" },
  { code: '7177', name: "ＧＭＯフィナンシャルホールディングス" },
  { code: '7208', name: "カネミツ" },
  { code: '7212', name: "エフテック" },
  { code: '7222', name: "日産車体" },
  { code: '7320', name: "Ｓｏｌｖｖｙ" },
  { code: '7325', name: "アイリックコーポレーション" },
  { code: '7343', name: "ブロードマインド" },
  { code: '7409', name: "ＡｅｒｏＥｄｇｅ" },
  { code: '7570', name: "橋本総業ホールディングス" },
  { code: '7687', name: "ミクリード" },
  { code: '7689', name: "コパ・コーポレーション" },
  { code: '7702', name: "ＪＭＳ" },
  { code: '7711', name: "助川電気工業" },
  { code: '7713', name: "シグマ光機" },
  { code: '7716', name: "ナカニシ" },
  { code: '7719', name: "東京衡機" },
  { code: '7722', name: "国際計測器" },
  { code: '7727', name: "オーバル" },
  { code: '7743', name: "シード" },
  { code: '7840', name: "フランスベッドホールディングス" },
  { code: '8131', name: "ミツウロコグループホールディングス" },
  { code: '8699', name: "ＨＳホールディングス" },
  { code: '9029', name: "ヒガシホールディングス" },
  { code: '9115', name: "明海グループ" },
  { code: '9204', name: "スカイマーク" },
  { code: '9450', name: "ファイバーゲート" },
  { code: '9501', name: "東京電力ホールディングス" },
];

test('keeps at least 760 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(152);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(152);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1200社');
  await expect(page.locator('#stat-confirmed')).toHaveText('760社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(760);
});

test('exposes every structured-expansion-batch-74 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
