import { test, expect } from '@playwright/test';

const expandedCompanies = [
  { code: '1333', name: "Ｕｍｉｏｓ" },
  { code: '1379', name: "ホクト" },
  { code: '1420', name: "サンヨーホームズ" },
  { code: '1430', name: "ファーストコーポレーション" },
  { code: '1438', name: "岐阜造園" },
  { code: '1450', name: "ＴＡＮＡＫＥＮ" },
  { code: '1491', name: "中外鉱業" },
  { code: '1515', name: "日鉄鉱業" },
  { code: '1605', name: "ＩＮＰＥＸ" },
  { code: '1662', name: "石油資源開発" },
  { code: '1716', name: "第一カッター興業" },
  { code: '1718', name: "美樹工業" },
  { code: '1810', name: "松井建設" },
  { code: '1822', name: "大豊建設" },
  { code: '2003', name: "日東富士製粉" },
  { code: '2009', name: "鳥越製粉" },
  { code: '2055', name: "日和産業" },
  { code: '2112', name: "塩水港精糖" },
  { code: '2114', name: "フジ日本" },
  { code: '2204', name: "中村屋" },
  { code: '2208', name: "ブルボン" },
  { code: '2216', name: "カンロ" },
  { code: '2221', name: "岩塚製菓" },
  { code: '2226', name: "湖池屋" },
  { code: '2268', name: "Ｂ－Ｒ サーティワン アイスクリーム" },
  { code: '2286', name: "林兼産業" },
  { code: '250A', name: "シマダヤ" },
  { code: '2654', name: "アスモ" },
  { code: '2666', name: "オートウェーブ" },
  { code: '2669', name: "カネ美食品" },
  { code: '2673', name: "夢みつけ隊" },
  { code: '2683', name: "魚喜" },
  { code: '2961', name: "日本調理機" },
  { code: '2962', name: "テクニスコ" },
  { code: '2970', name: "ＧＬＣ ＧＲＯＵＰ" },
  { code: '2984', name: "ヤマイチエステート" },
  { code: '2991', name: "ランドネット" },
  { code: '3002', name: "グンゼ" },
  { code: '3023', name: "ラサ商事" },
  { code: '3053', name: "ペッパーフードサービス" },
  { code: '3106', name: "倉敷紡績" },
  { code: '3201', name: "日本毛織" },
  { code: '3236', name: "プロパスト" },
  { code: '3241', name: "ウィル" },
  { code: '3242', name: "アーバネットコーポレーション" },
  { code: '3267', name: "フィル・カンパニー" },
  { code: '3302', name: "帝国繊維" },
  { code: '3315', name: "日本コークス工業" },
  { code: '3401', name: "帝人" },
  { code: '3420', name: "ケー・エフ・シー" },
  { code: '3421', name: "稲葉製作所" },
  { code: '3423', name: "エスイー" },
  { code: '3426', name: "アトムリビンテック" },
  { code: '3434', name: "アルファＣｏ" },
  { code: '3435', name: "サンコーテクノ" },
  { code: '3437', name: "特殊電極" },
  { code: '3439', name: "三ツ知" },
  { code: '3441', name: "山王" },
  { code: '3569', name: "セーレン" },
  { code: '3580', name: "小松マテーレ" },
  { code: '3864', name: "三菱製紙" },
  { code: '3865', name: "北越コーポレーション" },
  { code: '3877', name: "中越パルプ工業" },
  { code: '3941', name: "レンゴー" },
  { code: '3950', name: "ザ・パック" },
  { code: '4350', name: "メディカルシステムネットワーク" },
  { code: '4351', name: "山田再生系債権回収総合事務所" },
  { code: '5105', name: "ＴＯＹＯ ＴＩＲＥ" },
  { code: '5110', name: "住友ゴム工業" },
  { code: '5121', name: "藤倉コンポジット" },
  { code: '5122', name: "オカモト" },
  { code: '5185', name: "フコク" },
  { code: '5186', name: "ニッタ" },
  { code: '5192', name: "三ツ星ベルト" },
  { code: '5195', name: "バンドー化学" },
  { code: '5214', name: "日本電気硝子" },
  { code: '5232', name: "住友大阪セメント" },
  { code: '5233', name: "太平洋セメント" },
  { code: '5262', name: "日本ヒューム" },
  { code: '5269', name: "日本コンクリート工業" },
  { code: '5301', name: "東海カーボン" },
  { code: '5302', name: "日本カーボン" },
  { code: '5446', name: "北越メタル" },
  { code: '5458', name: "高砂鐵工" },
  { code: '5464', name: "モリ工業" },
  { code: '5484', name: "東北特殊鋼" },
  { code: '5603', name: "虹技" },
  { code: '5612', name: "日本鋳鉄管" },
  { code: '5644', name: "メタルアート" },
  { code: '5721', name: "エスクリプトエナジー" },
  { code: '5724', name: "アサカ理研" },
  { code: '5729', name: "日本精鉱" },
  { code: '5753', name: "日本伸銅" },
  { code: '5816', name: "オーナンバ" },
  { code: '5817', name: "ＪＭＡＣＳ" },
  { code: '5843', name: "ニッポンインシュア" },
  { code: '5845', name: "全保連" },
  { code: '5985', name: "サンコール" },
  { code: '5992', name: "中央発條" },
  { code: '7150', name: "島根銀行" },
  { code: '7183', name: "あんしん保証" },
  { code: '7185', name: "ヒロセ通商" },
  { code: '7191', name: "イントラスト" },
  { code: '7192', name: "日本モーゲージサービス" },
  { code: '7480', name: "スズデン" },
  { code: '7590', name: "タカショー" },
  { code: '7818', name: "トランザクション" },
  { code: '7820', name: "ニホンフラッシュ" },
  { code: '7821', name: "前田工繊" },
  { code: '7839', name: "ＳＨＯＥＩ" },
  { code: '7856', name: "萩原工業" },
  { code: '7864', name: "フジシールインターナショナル" },
  { code: '7867', name: "タカラトミー" },
  { code: '7912', name: "大日本印刷" },
  { code: '7951', name: "ヤマハ" },
  { code: '7974', name: "任天堂" },
  { code: '8383', name: "鳥取銀行" },
  { code: '8416', name: "高知銀行" },
  { code: '8508', name: "Ｊトラスト" },
  { code: '8518', name: "日本アジア投資" },
  { code: '8537', name: "大光銀行" },
  { code: '8563', name: "大東銀行" },
  { code: '8572', name: "アコム" },
  { code: '8596', name: "九州リースサービス" },
  { code: '8617', name: "光世証券" },
  { code: '8783', name: "ａｂｃ" },
  { code: '8841', name: "テーオーシー" },
  { code: '8864', name: "空港施設" },
  { code: '8869', name: "明和地所" },
  { code: '8918', name: "ランド" },
  { code: '9012', name: "秩父鉄道" },
  { code: '9017', name: "新潟交通" },
  { code: '9028', name: "ゼロ" },
  { code: '9034', name: "南総通運" },
  { code: '9036', name: "東部ネットワーク" },
  { code: '9049', name: "京福電気鉄道" },
  { code: '9127', name: "玉井商船" },
  { code: '9130', name: "共栄タンカー" },
  { code: '9171', name: "栗林商船" },
  { code: '9173', name: "東海汽船" },
  { code: '9193', name: "東京汽船" },
  { code: '9233', name: "アジア航測" },
  { code: '9306', name: "東陽倉庫" },
  { code: '9307', name: "杉村倉庫" },
  { code: '9311', name: "アサガミ" },
  { code: '9312', name: "ケイヒン" },
  { code: '9313', name: "丸八倉庫" },
  { code: '9322', name: "川西倉庫" },
  { code: '9327', name: "イー・ロジット" },
  { code: '9351', name: "東洋埠頭" },
  { code: '9369', name: "キユーソー流通システム" },
  { code: '9503', name: "関西電力" },
  { code: '9828', name: "Ｇｅｎｋｉ　Ｇｌｏｂａｌ　Ｄｉｎｉｎｇ　Ｃｏｎｃｅｐｔｓ" },
];

test('keeps at least 913 companies available for structured comparison', async ({ page }) => {
  expect(expandedCompanies).toHaveLength(153);
  expect(new Set(expandedCompanies.map(company => company.code)).size).toBe(153);
  await page.goto('/');
  await expect(page.locator('#stat-total')).toHaveText('1200社');
  await expect(page.locator('#stat-confirmed')).toHaveText('913社');
  const structuredCount = Number((await page.locator('#stat-structured').textContent()).replace(/[^0-9]/g, ''));
  expect(structuredCount).toBeGreaterThanOrEqual(913);
});

test('exposes every structured-expansion-batch-75 company through search and detail', async ({ page }) => {
  await page.goto('/');
  for (const company of expandedCompanies) {
    await page.locator('#search').fill(company.code);
    await expect(page.locator('.company-card')).toHaveCount(1);
    await expect(page.locator('.company-card')).toContainText(company.name);
    await page.locator('[data-detail]').click();
    await expect(page.locator('#company-dialog')).toBeVisible();
    await expect(page.locator('#company-dialog h2')).toContainText(company.name);
    await page.locator('#company-dialog [data-close]').click();
  }
});
