import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const ROOT=path.resolve('.'),SITE=path.join(ROOT,'site'),ART=path.join(ROOT,'artifacts'),checks=[],issues=[];
const MILESTONE=path.join(ROOT,'operations','quality','coverage-milestone-v1.json');
const milestone=fs.existsSync(MILESTONE)?JSON.parse(fs.readFileSync(MILESTONE,'utf8')):{companyTotal:570,progressRows:149};
const check=(name,ok,detail='')=>{checks.push({name,ok,detail});if(!ok)issues.push({name,detail});};
const required=['index.html','quality.html','404.html','manifest.webmanifest','robots.txt','_headers','assets/app.js','assets/search-core.js','assets/quality.js','assets/styles.css','data/bundle.manifest.json'];
for(const file of required)check(`${file} exists`,fs.existsSync(path.join(SITE,file)));
const netlify=fs.readFileSync(path.join(ROOT,'netlify.toml'),'utf8');
check('Netlify publish directory is site',/publish\s*=\s*["']site["']/.test(netlify));
check('Netlify build config has no secret literals',!/(token|password|secret)\s*=\s*["'][^"']+/i.test(netlify));
const bundle=JSON.parse(fs.readFileSync(path.join(SITE,'data','bundle.manifest.json'),'utf8'));
const parts=bundle.parts.map(part=>fs.readFileSync(path.join(SITE,'data',part.file)));
const compressed=Buffer.concat(parts),digest=crypto.createHash('sha256').update(compressed).digest('hex');
check('bundle part count matches',parts.length===bundle.parts.length,`actual=${parts.length}`);
check('bundle bytes match',compressed.length===bundle.compressedBytes,`actual=${compressed.length}`);
check('bundle SHA-256 matches',digest===bundle.sha256,digest);
check(`company count ${milestone.companyTotal}`,bundle.companyCount===milestone.companyTotal,`actual=${bundle.companyCount}`);
check(`progress count ${milestone.progressRows}`,bundle.progressCount===milestone.progressRows,`actual=${bundle.progressCount}`);
check('quality score v2 release',bundle.version==='v43-quality-score-v2',`actual=${bundle.version}`);
const publicText=required.filter(file=>/\.(html|js|css|json|webmanifest|txt)$/.test(file)).map(file=>fs.readFileSync(path.join(SITE,file),'utf8')).join('\n');
check('public files contain no obsolete v42 label',!/(Coverage 30% Beta v42|public_beta_v42|operations_v42)/i.test(publicText));
check('public files contain no localhost dependency',!/(localhost|127\.0\.0\.1):\d+/.test(publicText));
check('public files contain no obvious secrets',!/(api[_-]?key|client[_-]?secret|password)\s*[:=]\s*["'][^"']{8,}/i.test(publicText));
const release=JSON.parse(fs.readFileSync(path.join(ART,'release-manifest-v1.json'),'utf8'));
check('release manifest product',release.product==='Chu-kei');
check('release manifest publish directory',release.publishDirectory==='site');
check('release manifest version matches bundle',release.releaseVersion===bundle.version);
check('release manifest company count',release.companyCount===milestone.companyTotal,`actual=${release.companyCount}, expected=${milestone.companyTotal}`);
check('release manifest progress count',release.progressCount===milestone.progressRows,`actual=${release.progressCount}, expected=${milestone.progressRows}`);
check('release manifest data hash',release.dataBundle?.sha256===bundle.sha256);
check('release manifest file paths unique',new Set(release.files.map(file=>file.path)).size===release.files.length);
fs.mkdirSync(ART,{recursive:true});const report={version:'release-deployment-gate-v1',checkedAt:new Date().toISOString(),milestone,passed:checks.filter(c=>c.ok).length,total:checks.length,allPassed:issues.length===0,checks,issues};fs.writeFileSync(path.join(ART,'release-deployment-report-v1.json'),JSON.stringify(report,null,2)+'\n');for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}${c.detail?`: ${c.detail}`:''}`);process.exit(report.allPassed?0:1);
