import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
const root=path.resolve('site'),dataDir=path.join(root,'data'),checks=[],issues=[];
const check=(name,ok,detail='')=>{checks.push({name,ok,detail});if(!ok)issues.push({name,detail});};
const manifest=JSON.parse(fs.readFileSync(path.join(dataDir,'bundle.manifest.json'),'utf8'));
let payload={companies:[],progress:[]};
try{payload=JSON.parse(zlib.gunzipSync(Buffer.concat(manifest.parts.map(p=>fs.readFileSync(path.join(dataDir,p.file))))));check('quality source data readable',true);}catch(error){check('quality source data readable',false,error.message);}
const companies=payload.companies||[],detailed=companies.filter(c=>c.stage==='detailed_extracted');
const pageEvidence=c=>(c.evidenceRefs||[]).some(x=>/(?:p\.?\s*\d|ページ\s*\d)/i.test(String(x)));
check('quality dashboard HTML exists',fs.existsSync(path.join(root,'quality.html')));
check('quality dashboard JavaScript exists',fs.existsSync(path.join(root,'assets/quality.js')));
check('quality dashboard CSS exists',fs.existsSync(path.join(root,'assets/quality.css')));
check('detail beta queue has 70 companies',detailed.length===70,`actual=${detailed.length}`);
check('priority A candidates 17',detailed.filter(pageEvidence).length===17,`actual=${detailed.filter(pageEvidence).length}`);
check('priority B candidates 53',detailed.filter(c=>!pageEvidence(c)).length===53,`actual=${detailed.filter(c=>!pageEvidence(c)).length}`);
check('production publication date gaps 4',companies.filter(c=>c.stage==='core'&&!c.planPublishedDate).length===4);
check('production page evidence gaps 23',companies.filter(c=>c.stage==='core'&&!pageEvidence(c)).length===23);
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
check('dashboard linked from main navigation',index.includes('href="./quality.html"'));
const html=fs.readFileSync(path.join(root,'quality.html'),'utf8');
check('dashboard explains no automatic promotion',html.includes('本番昇格を自動決定しません'));
check('dashboard requires human review',html.includes('原文突合')&&html.includes('別確認者レビュー'));
const js=fs.readFileSync(path.join(root,'assets/quality.js'),'utf8');
check('dashboard verifies bundle SHA-256',js.includes("crypto.subtle.digest('SHA-256'"));
check('dashboard has no recommendation language',!['おすすめ銘柄','買い推奨','勝率'].some(term=>(html+js).includes(term)));
fs.mkdirSync('artifacts',{recursive:true});
const report={version:'quality-dashboard-v1',checkedAt:new Date().toISOString(),passed:checks.filter(c=>c.ok).length,total:checks.length,allPassed:issues.length===0,checks,issues};
fs.writeFileSync('artifacts/quality-dashboard-report-v1.json',JSON.stringify(report,null,2)+'\n');
for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}${c.detail?`: ${c.detail}`:''}`);
console.log(`\n${report.passed}/${report.total} checks passed`);
process.exit(report.allPassed?0:1);
